M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu23.04.1} date Wed Oct  4 13:43:30 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-10-04T13:43:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X22510Y11815
X28290Y11815
T0
M30
